version: "3.7"

services:
  gateway:
    image: canyan/janus-gateway:latest
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8088:8088"
      - "8188:8188"
      - "7088:7088"
    volumes:
      - "./etc:/usr/local/etc/janus"
